name: Build and Deploy
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Install and Build
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_SECRET: ${{ secrets.TRELLO_SECRET }}
        run: |
          npm install
          echo "window.TrelloConfig = { apiKey: '${{ secrets.TRELLO_API_KEY }}' };" > public/js/config.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js for deployment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy Server
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
        run: |
          # Add any server deployment steps here
          # For example, if deploying to Heroku:
          # git push heroku main