name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_SECRET: ${{ secrets.TRELLO_SECRET }}
        run: |
          npm install
          echo "window.TrelloConfig = { apiKey: '${{ secrets.TRELLO_API_KEY }}', secret: '${{ secrets.TRELLO_SECRET }}' };" > public/js/config.js