name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        run: |
          npm install
          echo "const TRELLO_API_KEY = '${{ secrets.TRELLO_API_KEY }}';" > public/config.js